int n1 = 3 + 4 * 2;
int n2 = (3 + 4) * 2;
int n3 = 17 % 3;
double n4 = 10.0 / 8.0;
double a = 1.0, b = -3.0, c = -4.0;
double delta = Math.Pow(b, 2.0) - 4.0 * a * c;
double x1 = (-b + Math.Sqrt(delta)) / (2.0 * a);
double x2 = (-b - Math.Sqrt(delta)) / (2.0 * a);
Console.WriteLine("O resultado da operação: 3 + 4 * 2 é " + n1);
Console.WriteLine("O resultado da operação: (3 + 4) * 2 é " + n2);
Console.WriteLine("O resultado da operação: 17 % 3 é " + n3);
Console.WriteLine("O resultado da operação: 17 % 3 é " + n4);
Console.WriteLine("O delta de bhaskara é" + delta);
Console.WriteLine("O x1 de bhaskara é" + x1);
Console.WriteLine("O x2 de bhaskara é" + x2);